FROM percona/percona-xtradb-cluster:5.7.16

RUN apt-get update \
&& apt-get install -y xinetd \
&& apt-get install -y lsb-release \
&& apt-get install -y wget \
&& wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb \
&& dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb \
&& apt-get update \
&& apt-get install -y percona-toolkit \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY clustercheck /usr/bin/
RUN chmod +x /usr/bin/clustercheck

COPY entrypoint.sh /
COPY percona_common/init_datadir.sh /init_datadir.sh
COPY percona_common/wait_mysql.sh /wait_mysql.sh

RUN chmod +x /entrypoint.sh
RUN chmod +x /init_datadir.sh
RUN chmod +x /wait_mysql.sh